Feat: Use Enum for the possible status options for a tranche
Amali-Tech/amalisov-cuibono pull request #12
Opened 2024-10-18 09:56 UTC by ishimwe07

## Tasks Completed
- [x] Create `enum` for bonus tranche status
- [x] Create `enum` for participant creation status
- [x] Expose `Department` entity to enable the expansion of an employee to get their department

2024-10-18 10:22 UTC, Bateyjosue requested changes
# Kudos @ishimwe07  implementing the feature
## Highlights
I left few comments
- the enum creation
- correct the typo on your message aformentioned

2024-10-18 10:22 UTC, Bateyjosue commented on src/handlers/update-bonusTranche.action.ts
>            400,
Oops! check the message. there is typo on `Completed` it is instead `complted`

2024-10-18 10:22 UTC, Bateyjosue commented on src/utils/types/api.ts
> +}
I have a reflection here, do you need the enum on the generated Javascript?
If not then why not `const` it so that it's not compiled as an object
Example:
```ts
const enum TrancheStatusEnum {
  Running,
  Locked,
  Completed,
}
 ```
Then can be accessed in the `src/utils/helpers/isTrancheStatusValid.ts`
```ts
const validStatusValues = [
  TrancheStatusEnum.Running,
  TrancheStatusEnum.Locked,
  TrancheStatusEnum.Completed,
];

```

2024-10-18 10:22 UTC, Bateyjosue commented on src/utils/types/api.ts
> +}
Same here!

2024-10-18 11:30 UTC, Bateyjosue approved these changes
# Nice work implementing the changes requested :tada:

2024-10-18 12:25 UTC, pmy09 commented on db/schema.cds
> +      status                    : String enum {
make it a type and reference it here

2024-10-18 12:26 UTC, pmy09 commented on db/schema.cds
> +      participantCreationStatus : String enum {
same here

2024-10-18 12:28 UTC, pmy09 commented on src/utils/types/api.ts
Whats the essence of this file ?

2024-10-18 12:29 UTC, pmy09 commented on src/handlers/bonusTranche.handler.ts
> +      const isStatusValid = isTrancheStatusValid(status);
If you handle your cds correctly, this check would be unnecessary

2024-10-18 12:31 UTC, pmy09 commented on src/handlers/bonusTranche.handler.ts
> +      if (status !== undefined && !isStatusValid) {
Also unnecessary

2024-10-18 12:40 UTC, pmy09 commented on src/utils/helpers/isTrancheStatusValid.ts
Completely unnecessary file

2024-10-18 12:41 UTC, pmy09 requested changes
Please check comments

2024-10-21 09:46 UTC, pmy09 commented on db/schema.cds
> +type TrancheStatusEnum             : String not null @assert.range enum {
String not null @assert.range enum is redundant here

2024-10-21 09:48 UTC, pmy09 commented on src/handlers/bonusTranche.handler.ts
> +      if (status === null) {
At what point is FE going to send you status null?

2024-10-21 09:50 UTC, pmy09 commented on src/handlers/update-bonusTranche.action.ts
> +      if (updatedTrancheData.status === null) {
Refer to previous comment

2024-10-21 09:50 UTC, ishimwe07 commented on db/schema.cds
> +type TrancheStatusEnum             : String not null @assert.range enum {
Hello @pmy09 , Thank you for the feedback, but for the `@assert.range enum` only check for the other values but if it is `null` is not rejected with that validation. So here we are checking for nullity also for status values because it can not make sense to have a status with value `null`. So I would appreciate your thoughts on this one.
Thank you!

2024-10-21 09:53 UTC, pmy09 commented on db/schema.cds
> +type TrancheStatusEnum             : String not null @assert.range enum {
By default enums in CAP are non-nullable

2024-10-21 09:55 UTC, pmy09 requested changes
Please review comments

2024-10-21 09:57 UTC, ishimwe07 commented on src/handlers/bonusTranche.handler.ts
> +      if (status === null) {
here we are handling any possible case where the user of our `api` can send a status with value null. And this is the same case as the checking for the dates we are pretty sure that they handled that, but still on the backend we had to check it too. So we thought that it must be handled since it can be sent and saved if not handled property.

2024-10-24 12:53 UTC, pmy09 approved these changes

2024-10-24 12:54 UTC, merged