feat: overrule participants
Amali-Tech/amalisov-cuibono pull request #18
Opened 2024-10-22 16:35 UTC by Bateyjosue

## In this PR

- [ ] Create action handler to overrule participants

2024-10-22 16:53 UTC, ishimwe07 requested changes
# Kudos @Bateyjosue   implementing the feature
## Highlights
I left few comments
- The over rule of the final amount and how it is being updated
- The return type of the action

2024-10-22 16:53 UTC, ishimwe07 commented on srv/service/bonusTranche.service.cds
> +    action overruleParticipant(participants: array of UUID, justification: String) returns TrancheParticipation;
For the return value, If user send many tranche participations to overrule the amount, which single tranche participation will be returned exactly?

2024-10-22 16:53 UTC, ishimwe07 commented on srv/service/bonusTranche.service.cds
> +    action overruleParticipant(participants: array of UUID, justification: String) returns TrancheParticipation;
For The overrule, It is the admin overruling the final amount of a participants, how is the new final amount is getting to the backend?

2024-10-22 16:53 UTC, ishimwe07 commented on src/handlers/overrule-participant.action.ts
> +      return {
The return value should be as the one mentioned while declaring an action in the service file.

2024-10-22 17:01 UTC, Bateyjosue commented on srv/service/bonusTranche.service.cds
> +    action overruleParticipant(participants: array of UUID, justification: String) returns TrancheParticipation;
Do you know the formula to calculate it??

2024-10-23 09:42 UTC, ishimwe07 approved these changes
# Nice work implementing the changes requested :tada:

2024-10-23 13:31 UTC, pmy09 approved these changes

2024-10-23 13:32 UTC, merged