feature: payout amount calculation
Amali-Tech/amalisov-cuibono pull request #26
Opened 2024-10-29 15:14 UTC by Bateyjosue

## Task description

- [ ] add helper functions for formulas 
- [ ] add function to calculate the payout amount `payoutCalculation`
- [ ] invoke the `payoutCalculation` when Locking a bonus Tranche

2024-10-30 16:07 UTC, Isaac-Ampomah-12 approved these changes

2024-10-30 16:30 UTC, pmy09 commented on src/handlers/excludeParticipants.action.ts
> +        if (participation.excluded) {
If it is excluded, why are you setting things as null and false?

2024-10-30 16:38 UTC, pmy09 commented on src/utils/helpers/proRataPerEmployee.ts
Same as above

2024-10-30 16:38 UTC, pmy09 requested changes
Please check comments

2024-10-30 16:39 UTC, ishimwe07 commented on src/handlers/excludeParticipants.action.ts
> +        if (participation.excluded) {
Here we were using one handler for excluding and re including the participants. Instead of creating another endpoint for it, we made this handler to toggle between exclude and re include the participant. Maybe you can give us a comment about it, or if we should create a different handler for re including a participant.
Thank you!

2024-10-30 16:44 UTC, ishimwe07 commented on src/utils/helpers/proRataPerEmployee.ts
I think I don't get the comment above you are referring to. Can you please elaborate more on this one?
Thank you!

2024-11-04 08:15 UTC, ishimwe07 approved these changes
## LGTM

2024-11-06 10:24 UTC, closed without merging