feat: create an action handler for retrieving bonuses payable
Amali-Tech/amalisov-cuibono pull request #27
Opened 2024-10-31 14:09 UTC by ishimwe07

## Tasks Completed

- [ ] Create an action handler to retrieve bonus payables

2024-10-31 14:53 UTC, Bateyjosue requested changes
## Great work
# 
I left an comment there check it out

2024-10-31 14:53 UTC, Bateyjosue commented on src/handlers/getBonusPayable.action.ts
> +  public async overruleParticipant(@ParamObj() data: Idata) {
Is it necessary to create an interface for only one property. couldn't you just use it directly?

like this:
```js
public async overruleParticipant(@Param("fiscalYear") fiscalYear: string)
```
> as we are pretty sure it will only be that

2024-10-31 15:20 UTC, Bateyjosue approved these changes
## LGTM, Kudos :tada:

2024-11-04 15:11 UTC, pmy09 approved these changes

2024-11-04 15:12 UTC, merged