Feat/Bonus Payable
Amali-Tech/amalisov-cuibono pull request #29
Opened 2024-11-05 10:28 UTC by ishimwe-rodrigue

Task description
view items in the bonus payable page
Disable previous dates on the begin date

2024-11-05 14:25 UTC, Michael-amali commented on app/amalisov.cuibono/webapp/controller/BonusPayable.controller.ts
> +            const oContext = await oModel.bindList("/bonusPayable").requestContexts(0, 100);
Explain what this line of code does, .requestContexts(0, 100);

2024-11-05 14:26 UTC, Christopher-Angoe commented on app/amalisov.cuibono/webapp/i18n/i18n.properties
> +errorDispayingData= erro dispaying Bonus Payable data
missing an r at the end of error

2024-11-05 14:27 UTC, Michael-amali requested changes
Check comment

2024-11-05 14:28 UTC, Michael-amali commented on app/amalisov.cuibono/webapp/i18n/i18n.properties
> +errorDispayingData= erro dispaying Bonus Payable data
And the "displaying"

2024-11-05 14:37 UTC, ishimwe-rodrigue commented on app/amalisov.cuibono/webapp/controller/BonusPayable.controller.ts
> +            const oContext = await oModel.bindList("/bonusPayable").requestContexts(0, 100);
this line is used the fetch the request 100 items so 0, 100  are the index

2024-11-05 14:40 UTC, Michael-amali commented on app/amalisov.cuibono/webapp/controller/BonusPayable.controller.ts
> +            const oContext = await oModel.bindList("/bonusPayable").requestContexts(0, 100);
So if there are more than 100 items, what happens ?

2024-11-05 14:58 UTC, ishimwe-rodrigue commented on app/amalisov.cuibono/webapp/controller/BonusPayable.controller.ts
> +            const oContext = await oModel.bindList("/bonusPayable").requestContexts(0, 100);
it doesnt show more than 100 as the method requestContexts show the length of 100 items even though i removed (0, 100) as i think 100 is the default

2024-11-05 15:13 UTC, Christopher-Angoe approved these changes

2024-11-05 15:16 UTC, Michael-amali commented on app/amalisov.cuibono/webapp/controller/BonusPayable.controller.ts
> +            const oContext = await oModel.bindList("/bonusPayable").requestContexts(0, 100);
What really ?

2024-11-05 15:26 UTC, ishimwe-rodrigue commented on app/amalisov.cuibono/webapp/controller/BonusPayable.controller.ts
> +            const oContext = await oModel.bindList("/bonusPayable").requestContexts(0, 100);
i tried it doesnt work i even asked for help from team c i decided to use the controller
maybe i can show it you

2024-11-06 08:23 UTC, Michael-amali approved these changes
ok

2024-11-06 10:00 UTC, merged