Creation of entities
Amali-Tech/amalisov-cuibono pull request #3
Opened 2024-09-30 14:52 UTC by ishimwe07

## Tasks completed

- [x] Create entities
- [x] Install `cds-routing-handler`
- [x] Install `@cap-js/cds-typer`
- [x] Install `typedi`
- [x] Import `reflect-metadata` globally 
- [x] Ignore files in `@cds-models` while linting

2024-09-30 15:10 UTC, Bateyjosue approved these changes
Nice work done :tada: :tada: 
#
## LGTM

2024-09-30 15:12 UTC, Bateyjosue approved these changes
## LGTM

2024-10-01 11:59 UTC, pmy09 commented on db/schema.cds
> +entity TrancheParticipation {
This is incomplete

2024-10-01 12:00 UTC, pmy09 commented on package.json
> +    "gen-types": "npx @cap-js/cds-typer \"*\" --outputDirectory @cds-models",
please remove this

2024-10-01 12:02 UTC, pmy09 requested changes
Please address the issues

2024-10-02 16:04 UTC, pmy09 approved these changes

2024-10-02 16:06 UTC, merged