Feature/calculations
Amali-Tech/amalisov-cuibono pull request #31
Opened 2024-11-06 10:09 UTC by ishimwe07

## Tasks Completed
- [x] add helper functions for formulas 
- [x] add function to calculate the payout amount `payoutCalculation`
- [x] invoke the `payoutCalculation` when Locking a bonus Tranche
- [x] check if the tranche falls in a fiscal year while editing
- [x] assign final amounts when completing a tranche
- [x] Include someone who was excluded before
- [ ] Calculate bonus payable for each fiscal year with completed tranches
- [ ] All weight for tranches in same fiscal year should not exceed 100% on bonus tranche create

2024-11-06 16:27 UTC, pmy09 commented on src/handlers/getBonusPayable.action.ts
> +        (employeeRecord: QLExtensions<Required<Employee>>) => {
CAP already has a way of handling this scenario:

`await SELECT.from(Employee)
.columns(c => {
c("*"), c.trancheParticipation(participation) => {} ............
})`

2024-11-06 16:30 UTC, pmy09 commented on src/handlers/update-bonusTranche.action.ts
> +        .columns((bonuses) => [
You have it implemented here so why not above?

2024-11-06 16:34 UTC, pmy09 requested changes
Please check the comment and implement it for consistency

2024-11-06 16:34 UTC, Isaac-Ampomah-12 approved these changes

2024-11-07 09:27 UTC, pmy09 approved these changes

2024-11-07 09:30 UTC, Isaac-Ampomah-12 approved these changes

2024-11-07 09:38 UTC, Bateyjosue approved these changes
## LGTM :tada:

2024-11-07 10:00 UTC, merged