Feature: add fields and restrict on bonus tranche creation
Amali-Tech/amalisov-cuibono pull request #6
Opened 2024-10-07 22:36 UTC by Bateyjosue

In this PR, we work on 

- [ ]  restricting  not creating a bonus tranche with more than a 100% 
- [ ] adding date of origin field to the bonus tranche
- [ ] adding a description field to the target

2024-10-08 09:42 UTC, ishimwe07 approved these changes
Good job, it looks good to me.
Though I left you some comments, you can check them out.

And in addition to those comments, in the specification the bonus tranche with status `locked` can not be `updated` or `deleted`, so I was wondering about where was that handled, maybe this can be considered to.

But after all... 👇🏿 
 
![kudos-oprah](https://github.com/user-attachments/assets/166cdca6-0a75-454a-a3aa-24cb322b7837)

2024-10-08 09:42 UTC, ishimwe07 commented on src/handlers/bonusTranche.handler.ts
>      } catch (error: unknown) {
In catch block you don't catch the error and throw a new one. You catch it, and you log it using logger and then throw it again so that you can be able to debug. If it is done like that you will never know what the error is, you will only know where the error is.

2024-10-08 09:42 UTC, ishimwe07 commented on src/handlers/bonusTranche.handler.ts
>        // Delete all targets before updating them
are the comments, really necessary?

2024-10-09 07:38 UTC, pmy09 commented on src/handlers/bonusTranche.handler.ts
> +      req.data.trancheWeight = totalTargetsWeight;
why are you equating tranche weight to target weight

2024-10-09 07:41 UTC, pmy09 commented on src/handlers/bonusTranche.handler.ts
>      } catch (error: unknown) {
I also don't want to see 'any', 'unknown' or 'undefined' types

2024-10-09 07:42 UTC, pmy09 commented on src/handlers/bonusTranche.handler.ts
> +      req.data.trancheWeight = totalTargetsWeight;
Same as earlier comment

2024-10-09 07:43 UTC, pmy09 requested changes
Please fix issues

2024-10-09 08:58 UTC, pmy09 approved these changes

2024-10-09 09:02 UTC, merged