Update Bonus Tranche Action
Amali-Tech/amalisov-cuibono pull request #9
Opened 2024-10-16 09:58 UTC by ishimwe07

## Tasks completed
- [x] Create an action for editing bonus tranche
- [x] Remove before update handler for bonus tranche

2024-10-16 10:50 UTC, Bateyjosue requested changes
## Hey @ishimwe07, Nice work done so far
### Highlight
I left comments related to:

- [ ] Typing dates in the bonusTrancheInterface;
- [ ] Handling other edge cases on the status and the update functionality
#
# Kudos :tada: :tada:

2024-10-16 10:50 UTC, Bateyjosue commented on src/handlers/update-bonusTranche.action.ts
> +  dateOfOrigin: string;
I thought the dates were typed as Datetime while creating the entity what is the point of typing it a string in this interface?
Entity:
```cds
entity BonusTranche: managed {
  key ID                   : UUID;
      name                 : String(50) @mandatory;
      description          : String;
      beginDate            : DateTime @mandatory;
      endDate              : DateTime @mandatory;
      dateOfOrigin         : DateTime @mandatory;
      status               : String default 'Running';
      trancheWeight        : Decimal;
      Target               : Association to many Target
                              on Target.BonusTranche = $self;
      trancheParticipation : Association to many TrancheParticipation
                              on trancheParticipation.bonusTranche = $self;
      Location             : Association to Location;
}
```

2024-10-16 10:50 UTC, Bateyjosue commented on src/handlers/update-bonusTranche.action.ts
> +      }
Is it there any other status that can prevent the update, like `Completed`. if so then I would suggest adding it in the check as well

2024-10-16 12:48 UTC, Bateyjosue approved these changes
# LGTM :tada:  Kudos

2024-10-16 18:09 UTC, pmy09 requested changes
Please check comment

2024-10-16 18:12 UTC, ishimwe07 commented on src/handlers/update-bonusTranche.action.ts
> +      if (
Well according to the specifications we referred to, the tranche with status `Locked` can not be edited and deleted anymore. Then In this case it can't be updated to `Running` anymore.

![image](https://github.com/user-attachments/assets/cec8d20d-78dc-4a30-9cca-575068b7f33f)

2024-10-17 11:03 UTC, pmy09 commented on src/handlers/update-bonusTranche.action.ts
> +        trancheToUpdate.status === "Locked" &&
And if the status is being changed from Locked to Completed?

2024-10-17 11:03 UTC, pmy09 requested changes
check comment

2024-10-17 13:04 UTC, pmy09 approved these changes

2024-10-17 13:07 UTC, merged